Spring:
  datasource: 
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/Xworkz
     username: root
     password: Xworkzodc@123
  jpa:
   show-sql: true   
   generate-ddl: true   
   hibernate:
     ddl-auto: update
   properties:
     hibernate:
       format-sql: true 
  properties:
     hibernate: 
       dialect: org.hibernate.dialect.MySQL8Dialect
---
logging:
 level:
   org:
    springframework: TRACE
---
Server:
    port: 8081
---
spring:
   profiles: 
     active: prod
---
  
logging:
  level: 
    org.springframework: INFO
--- 
spring:
  output:
    ansi:
      enabled: Always 
    
        
  

         
    
         